"""New Migration

Revision ID: 649dfe15ba74
Revises: 5bf96488c990
Create Date: 2021-08-15 12:13:06.205178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649dfe15ba74'
down_revision = '5bf96488c990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
