"""New Migration

Revision ID: a170013a7b48
Revises: 649dfe15ba74
Create Date: 2021-09-18 17:39:10.861576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a170013a7b48'
down_revision = '649dfe15ba74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
